macro(common_set_ANDROID_PACKAGE_SOURCE_DIR TARGET ANDROID_PACKAGE_SOURCE_DIR_PATH)
    if(ANDROID)
        set(ANDROID_PACKAGE_SOURCE_DIR "${ANDROID_PACKAGE_SOURCE_DIR_PATH}")
        set(__ANDROID_PACKAGE_FILES "")
        file(GLOB_RECURSE __ANDROID_PACKAGE_FILES ${ANDROID_PACKAGE_SOURCE_DIR}/*)
        if ("${__ANDROID_PACKAGE_FILES}" STREQUAL "")
            message(NOTICE "ANDROID_PACKAGE_SOURCE_DIR is empty")
        else ()
            foreach (item ${__ANDROID_PACKAGE_FILES})
                message(NOTICE <-- ${item})
            endforeach ()
            add_custom_target(${TARGET}_ANDROID_PACKAGE_SOURCE_DIR ${__ANDROID_PACKAGE_FILES})
            set(__ANDROID_PACKAGE_FILES "")
        endif ()
    endif()
endmacro(common_set_ANDROID_PACKAGE_SOURCE_DIR)

#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
function(common_remove_files SEARCH_PATH)
    if(${ARGC} EQUAL 1)
        file(GLOB_RECURSE TMP_FINDED_FILES "${SEARCH_PATH}/*")
        foreach(x IN ITEMS ${TMP_FINDED_FILES})
            file(REMOVE ${x})
        endforeach ()
    else()
        foreach (item IN ITEMS ${ARGN})
            file(GLOB_RECURSE TMP_FINDED_FILES "${SEARCH_PATH}/${item}")
            foreach(x IN ITEMS ${TMP_FINDED_FILES})
                file(REMOVE ${x})
            endforeach ()
        endforeach ()
    endif()
endfunction(common_remove_files)

#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=#
function(common_get_cmake_variables)
    message("--- common_get_cmake_variables ---")
    get_cmake_property(names VARIABLES)
    list (SORT names)
    if(${ARGC} EQUAL 0)
        foreach (name ${names})
            message("VAR: ${name}=${${name}}")
        endforeach()
    else()
        foreach(arg IN ITEMS ${ARGN})
            foreach (name ${names})
                if("${arg}" STREQUAL "${name}")
                    message("VAR: ${name}=${${name}}")
                endif()
            endforeach()
        endforeach()
    endif()
    message("----------------------------------")
endfunction()
